---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: workshop
spec:
  identityProviders:
  - name: workshop_htpasswd_provider
    challenge: true
    login: true
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: workshop-htpass-secret